In [352]:
import pandas as pd

In [353]:
df = pd.read_excel(r'C:\Users\acer\Documents\MEGA\Programming\ASPIRE\Python\data projects\simple_data_analy_viz\cleaning_calls\Customer Call List.xlsx', index_col=0)

In [354]:
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df = df.drop_duplicates()
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df['Last_Name'] = df['Last_Name'].str.strip('123./_')
df = df.dropna(subset=['Last_Name'])
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [357]:
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '', regex=True)
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:])
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
1003,Walter,White,,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,,1209 South Street,No,No
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,,3498 Super Lane,Y,NaN
1019,Creed,Braton,,N/a,N/a,Yes
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [359]:
df[['Street Adress', 'State', 'Zip']] = df['Address'].str.split(',' ,expand=True)
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,NaN,NaN
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
1019,Creed,Braton,,N/a,N/a,Yes,N/a,NaN,NaN
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

In [ ]:
df['Do_Not_Contact']= df['Do_Not_Contact'].replace('Y', 'Yes').replace('N', 'No')
df['Paying Customer']= df['Paying Customer'].replace('Y', 'Yes').replace('N', 'No')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
1003,Walter,White,,298 Drugs Driveway,No,NaN,298 Drugs Driveway,NaN,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,NaN,NaN
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,NaN,NaN
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,NaN,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,NaN,2394 Hogwarts Avenue,NaN,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,NaN,NaN
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,NaN,NaN
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,NaN,NaN
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
1018,Clark,Kent,,3498 Super Lane,Yes,NaN,3498 Super Lane,NaN,NaN
1019,Creed,Braton,,N/a,N/a,Yes,N/a,NaN,NaN
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,NaN

In [361]:
df = df.replace('N/a', '')
df = df.fillna('')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,,
1003,Walter,White,,298 Drugs Driveway,No,,298 Drugs Driveway,,
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,,
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,,
1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,
1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,,2394 Hogwarts Avenue,,
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,
1018,Clark,Kent,,3498 Super Lane,Yes,,3498 Super Lane,,
1019,Creed,Braton,,,,Yes,,,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,

In [362]:
df = df.drop(df[df['Do_Not_Contact'] == 'Yes'].index)
# df = df.drop(df[df['Phone_Number'] == ''].index)
# df = df.drop(df[df['Do_Not_Contact'] == 'Yes'].index)
df['Do_Not_Contact'] = df['Do_Not_Contact'].replace('', 'No')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,
1003,Walter,White,,298 Drugs Driveway,No,No,298 Drugs Driveway,,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,,
1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,
1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,No,2394 Hogwarts Avenue,,
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,
1018,Clark,Kent,,3498 Super Lane,Yes,No,3498 Super Lane,,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,

In [363]:
df = df.drop(df[df['Phone_Number'] == ''].index)
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,

In [364]:
# df = df.drop(columns = 'Zip')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Adress,State,Zip
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123 Dragons Road,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98 Clue Drive,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,No,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910 Tatooine Road,Tatooine,